[[maintenance]]
= Maintenance

[partintro]
--
This section describes the approach taken to the maintenance of the Platform.
--



[[maintenance-adding-dependencies]]
== Adding dependencies

The inclusion of a dependency in the Platform is triggered by its usage in one of the
Platform's projects. When a new project is added to the Platform, or the Platform upgrades
to a new version of an existing project, any of the project's dependencies that are not
part of the Platform will be added to the Platform. Furthermore, when a new dependency is
added to the Platform, any other modules that are part of the same project will typically
also be added, even if they are not using by any of the Platform's projects. This helps
to ensure that a consistent version is used across all modules of a third-party project.



[[maintenance-release-cycle]]
== Release cycle

A new maintenance release of the Platform occurs roughly every 6 to 8 weeks. There will,
however, be occasions when a new release occurs more quickly than this; to address a
security vulnerability, for example. This schedule will also slow down as a branch ages
and has been superceded.

In addition to the general maintenance cycle described above, a maintenance release of the
Platform will often be triggered by a maintenance release of Spring Boot. Furthermore,
a new maintenance release of Spring Framework will often trigger a maintenance release of
Spring Boot.

A key goal of the Platform is to provide its users with a stable set of versions that
maintain backwards compatibility while also being as up-to-date as possible. To allow us
to strike this balance there may be occasions when a bug in Spring Framework or Spring
Boot causes the Platform to skip a version and wait for a release which resolves the
issue.