[[upgrading]]
= Upgrading

[partintro]
--
This section provides all you need to know about upgrading to this version of Spring IO Platform.
--



[[upgrading-removal]]
== Removal of previously deprecated components

A number of the Platform's components that were deprecated in earlier releases have now been
removed.

=== platform-versions artifact

The `platform-versions` properties artifact has been removed. Maven users are unaffected by this
change. If, however, you're using the Platform with Gradle, then you must start using the
dependency management plugin and the Platform's bom instead. See
<<getting-started-using-spring-io-platform-gradle>> for more information.

=== Ant

Dependency management for four Ant dependencies has been removed. Thoses dependencies are:

 * `org.apache.ant:ant`
 * `org.apache.ant:ant-antlr`
 * `org.apache.ant:ant-junit`
 * `org.apache.ant:ant-launcher`

They are no longer a dependency of any of the Platform's projects.

=== bsf:bsf

Dependency management for `bsf:bsf` has been removed. It is no longer a dependency of any of the
Platform's projects.

=== Codahale metrics

Dependency management for four Codahale metrics dependencies has been removed. Those dependencies
are:

 * `com.codahale.metrics:metrics-core`
 * `com.codahale.metrics:metrics-ganglia`
 * `com.codahale.metrics:metrics-graphite`
 * `com.codahale.metrics:metrics-servlets`

The following dependencies should be used instead:

 * `io.dropwizard.metrics:metrics-core`
 * `io.dropwizard.metrics:metrics-ganglia`
 * `io.dropwizard.metrics:metrics-graphite`
 * `io.dropwizard.metrics:metrics-servlets`

=== com.beust:jcommander

Dependency management for `com.beust:jcommander` has been removed. It is no longer a dependency of
any of the Platform's projects.

=== com.lmax:disruptor

Dependency management for `com.lmax:disruptor` has been removed. Reactor now embeds a
repackaged version of the library so a dependency on `com.lmax:disruptor` is no longer
required.

=== com.thoughtworks.qdox:qdox

Dependency management for `com.thoughtworks.qdox:qdox` has been removed. It is no longer a
dependency of any of the Platform's projects.

=== net.java.dev.rome:rome

Dependency management for `net.java.dev.rome:rome` has been removed. `com.rometools:rome` should be
used instead.

=== net.java.dev.rome:rome-fetcher

Dependency management for `net.java.dev.rome:rome-fetcher` has been removed.
`com.rometools:rome-fetcher` should be used instead.

=== org.apache.cassandra:cassandra-all

Dependency management for `org.apache.cassandra:cassandra-all` has been removed.

=== org.apache.directory.server:apacheds-all

Dependency management for `org.apache.directory.server:apacheds-all` has been removed. Dependencies
on the more finely grained `org.apache.directory.server` modules should be used instead.

=== org.apache.ivy:ivy

Dependency management for `org.apache.ivy:ivy` has been removed. It is no longer a dependency of
any of the Platform's projects.

=== org.apache.tomcat:tomcat7-websocket

Dependency management for `org.apache.tomcat:tomcat7-websocket` has been removed. The equivalent
Tomcat 8 dependency, `org.apache.tomcat:tomcat-websocket`, should be used instead.

=== org.codehaus.gpars:gpars

Dependency management for `org.codehaus.gpars:gpars` has been removed. It is no longer a
dependency of any of the Platform's projects.

=== org.eclipse.paho:mqtt-client

Dependency management for `org.eclipse.paho:mqtt-client` has been removed.
`org.eclipse.paho:org.eclipse.paho.client.mqttv3` should be used instead.

=== org.erlang.otp:jinterface

Dependency management for `org.erlang.otp:jinterface` has been removed. It is no longer a
dependency of any of the Platform's projects.

=== org.fusesource.jansi:jansi

Dependency management for `org.fusesource.jansi:jansi` has been removed. It is no longer a
dependency of any of the Platform's projects.

=== org.glassfish.tyrus:tyrus-websocket-core

Dependency management for `org.glassfish.tyrus:tyrus-websocket-core` has been removed. It does
not exist in the version of Tyrus that is used by the Platform.

=== org.grails:grails-dependencies

Dependency management for `org.grails:grails-dependencies has been removed. Grails is no longer a
part of the Platform.

=== org.igniterealtime.smack:smackx

Dependency management for `org.igniterealtime.smack:smackx` has been removed. It does not exist in
the version of Smack that is used by the Platform.

=== org.hibernate.javax.persistence:hibernate-jpa-2.0-api

Dependency management for `org.hibernate.javax.persistence:hibernate-jpa-2.0-api` has been removed.
`org.eclipse.persistence:javax.persistence` should be used instead.

=== org.neo4j:neo4j-graph-collections

Dependency management for `org.neo4j:neo4j-graph-collections` has been removed.

=== org.springframework.amqp:spring-erlang

Dependency management for `org.springframework.amqp:spring-erlang` has been removed. It no longer
exists in the verison of Spring AMQP that is used by the Platform.
