[[upgrading]]
= Upgrading

[partintro]
--
This section provides all you need to know about upgrading to this version of Spring IO Platform.
--



[[upgrading-removal]]
== Removal of previously deprecated components

A number of the Platform's components that were deprecated in earlier releases have now been
removed.

=== platform-versions artifact

The `platform-versions` properties artifact has been removed. Maven users are unaffected by this
change. If, however, you're using the Platform with Gradle, then you must use the properties file
published by `platform-bom` instead:

[source,groovy,indent=0,subs="verbatim,attributes"]
----
	dependencies {
		versionManagement 'io.spring.platform:platform-bom:{platform-version}@properties'
	}
----

=== Codahale metrics

Dependency management for four Codahale metrics dependencies has been removed. Those dependencies
are:

 * `com.codahale.metrics:metrics-core`
 * `com.codahale.metrics:metrics-ganglia`
 * `com.codahale.metrics:metrics-graphite`
 * `com.codahale.metrics:metrics-servlets`

The following dependencies should be used instead:

 * `io.dropwizard.metrics:metrics-core`
 * `io.dropwizard.metrics:metrics-ganglia`
 * `io.dropwizard.metrics:metrics-graphite`
 * `io.dropwizard.metrics:metrics-servlets`

=== net.java.dev.rome:rome

Dependency management for `net.java.dev.rome:rome` has been removed. `com.rometools:rome` should be
used instead.

=== net.java.dev.rome:rome-fetcher

Dependency management for `net.java.dev.rome:rome-fetcher` has been removed.
`com.rometools:rome-fetcher` should be used instead.

=== org.apache.cassandra:cassandra-all

Dependency management for `org.apache.cassandra:cassandra-all` has been removed.

=== org.apache.tomcat:tomcat7-websocket

Dependency management for `org.apache.tomcat:tomcat7-websocket` has been removed. The equivalent
Tomcat 8 dependency, `org.apache.tomcat:tomcat-websocket`, should be used instead.

=== org.glassfish.tyrus:tyrus-websocket-core

Dependency management for `org.glassfish.tyrus:tyrus-websocket-core` has been removed. It does
not exist in the version of Tyrus that is used by the Platform.

=== org.igniterealtime.smack:smackx

Dependency management for `org.igniterealtime.smack:smackx` has been removed. It does not exist in
the version of Smack that is used by the Platform.

=== org.neo4j:neo4j-graph-collections

Dependency management for `org.neo4j:neo4j-graph-collections` has been removed.
